const data = {
    products: [
        {
            _id: '1',
            name: 'Warrior Yuknu',
            category: 'Yuknus',
            image: '/images/Y1.jpg',
            price: 34.99,
            countInStock: 10,
            rating: 5,
            numReviews: 10,
            description: 'hand made product',
        },
        {
            _id: '2',
            name: 'Zombie Yuknu',
            category: 'Yuknus',
            image: '/images/Y2.jpg',
            price: 34.99,
            countInStock: 15,
            rating: 3.5,
            numReviews: 10,
            description: 'hand made product',
        },
        {
            _id: '3',
            name: 'Forest Yuknu',
            category: 'Yuknus',
            image: '/images/Y3.jpg',
            price: 34.99,
            countInStock: 10,
            rating: 5,
            numReviews: 10,
            description: 'hand made product',
        },
        {
            _id: '4',
            name: 'Rune Yuknu',
            category: 'Yuknus',
            image: '/images/Y4.jpeg',
            price: 34.99,
            countInStock: 20,
            rating: 4.5,
            numReviews: 10,
            description: 'hand made product',
        },
        {
            _id: '5',
            name: 'Warrior Yuknu',
            category: 'Yuknus',
            image: '/images/Y1.jpg',
            price: 34.99,
            countInStock: 0,
            rating: 5,
            numReviews: 10,
            description: 'hand made product',
        },
        {
            _id: '6',
            name: 'Zombie Yuknu',
            category: 'Yuknus',
            image: '/images/Y2.jpg',
            price: 34.99,
            countInStock: 15,
            rating: 4.5,
            numReviews: 10,
            description: 'hand made product',
        },
    ],
}
export default data;